services:
  api: &main_app
    build:
      context: .
      dockerfile: ./Dockerfile
    image: pad:${PAD_VERSION:-latest}
    restart: always
    env_file:
      - path: .env
        required: false
    depends_on:
      mongo:
        condition: service_healthy
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      PAD_HOST: 0.0.0.0
      PAD_RELOAD: "false"
      PAD_MONGO_HOST: pad-mongo
      PAD_MONGO_PORT: 27017
      PAD_MONGO_USER: pad
      PAD_MONGO_PASS: pad
      PAD_MONGO_DB: pad
      PAD_POSTGRES_HOST: pad-postgres
      PAD_POSTGRES_PORT: 5432
      PAD_POSTGRES_USER: pad
      PAD_POSTGRES_PASS: pad
      PAD_POSTGRES_DB: pad

  mongo:
    image: mongo:7.0
    hostname: pad-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "pad"
      MONGO_INITDB_ROOT_PASSWORD: "pad"
    command: "mongod"
    volumes:
      - pad-mongo-data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: >
        mongosh --quiet --username pad --password pad
        --authenticationDatabase admin --eval "db.adminCommand('ping').ok"
      interval: 10s
      timeout: 5s
      retries: 40

  postgres:
    image: postgres:16-alpine
    hostname: pad-postgres
    restart: always
    environment:
      POSTGRES_USER: "pad"
      POSTGRES_PASSWORD: "pad"
      POSTGRES_DB: "pad"
    volumes:
      - pad-postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pad -d pad"]
      interval: 10s
      timeout: 5s
      retries: 40

volumes:
  pad-mongo-data:
    name: pad-mongo-data
  pad-postgres-data:
    name: pad-postgres-data
